In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.  
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

In [2]:

school_name=school_data_complete["school_name"]
number_students=len(school_data_complete["student_name"])


total_schools=len(school_name.unique())



total_budget=sum(school_data["budget"].unique())





math_score_mean=round(school_data_complete["math_score"].mean(),5)



reading_score_mean=round(school_data_complete["reading_score"].mean(),5)



school_data_complete
#Percentage of students who passed math 
passing_score_df=school_data_complete.loc[school_data_complete["math_score"]>=70 , :]
passing_score_math=passing_score_df["math_score"].count()*100
passing_percentage_math=passing_score_math/number_students


#Percentage of students who passed reading
passing_score_df=school_data_complete.loc[school_data_complete["reading_score"]>=70 , :]
passing_score_reading=passing_score_df["reading_score"].count()*100
passing_percentage_reading=passing_score_reading/number_students


#Percentage of students who passed both
passing_score_df=school_data_complete.loc[(school_data_complete["reading_score"] >=70) & (school_data_complete["math_score"]>=70), ["student_name", "reading_score", "math_score"]]
passing_student=passing_score_df["student_name"].count()*100
passing_percentage_total=passing_student/number_students


#Create Data Frame to summarize information
School_DataSummary_df=pd.DataFrame({"Total Schools": [total_schools], 
                                   "Total Students": [number_students],
                                   "Total Budget": [total_budget], 
                                   "Average Math Score": [math_score_mean],
                                   "Average Reading Score": [reading_score_mean], 
                                   "% Passing Math": [passing_percentage_math],
                                   "% Passing Reading": [passing_percentage_reading], 
                                   "% Overall Passing": [passing_percentage_total]})

School_DataSummary_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,39170,24649428,78.98537,81.87784,74.980853,85.805463,65.172326

In [115]:

school_summary_df=school_data_complete[["school_name", "type", "reading_score", "math_score", "size", "budget", "math_score", "reading_score"]]

school_summary_df=school_summary_df.groupby(["school_name"]).mean()

school_summary_df["Budget per student"]=school_summary_df["budget"]/school_summary_df["size"]




passing_score_math_df=school_data_complete.loc[school_data_complete["math_score"]>=70 , :]

passing_score_reading_df=school_data_complete.loc[school_data_complete["reading_score"]>=70 , :]

total_pass_math=passing_score_math_df.groupby(["school_name"]).count()["math_score"]

total_pass_reading=passing_score_reading_df.groupby(["school_name"]).count()["reading_score"]


total_students_school=school_data_complete.groupby(["school_name"]).count()["student_name"]



school_summary_df["% Passing Math"]=(total_pass_math/total_students_school)*100

school_summary_df["% Passing Reading"]=(total_pass_reading/total_students_school)*100

school_summary_df["type"]=school_data_complete.groupby(["school_name"])["type"].unique()


passing_both_df=school_data_complete.loc[(school_data_complete["math_score"]>=70) & (school_data_complete["reading_score"]>=70), :]




passing_both_df.groupby(["school_name"])["math_score"].count()

school_name
Bailey High School       2719
Cabrera High School      1697
Figueroa High School     1569
Ford High School         1487
Griffin High School      1330
Hernandez High School    2481
Holden High School        381
Huang High School        1561
Johnson High School      2549
Pena High School          871
Rodriguez High School    2119
Shelton High School      1583
Thomas High School       1487
Wilson High School       2068
Wright High School       1626
Name: math_score, dtype: int64